### ISSUE TITLE
Delete extra @import from SCSS files

### ISSUE THREAD

**Issue by dolbilov** [dolbilov/dont-get-wet#41]
в scss если используете @import, то повторное включение не нужно, все что включили в index будет видно везде. Индивидуально включать нужно с @use

**Comment by BKonstantine** [comment]
Вот этот комментарий не понял если честно

**Comment by dolbilov** [comment]
We should use `@use` (lol) instead of `@import` in the SCSS files. For example. You use variables in the `card` block. You need to kinda import this variables into `_card.scss`. And we should use `@use` in this case.

**Comment by dolbilov** [comment]
Done in PR #45
