### ISSUE TITLE
Find SVG icons for all weather types.

### ISSUE THREAD

**Issue by dolbilov** [dolbilov/dont-get-wet#6]

**Comment by BKonstantine** [comment]
I think we can use it https://icons8.ru/icon/set/%D0%BF%D0%BE%D0%B3%D0%BE%D0%B4%D0%B0/small or https://www.flaticon.com/ru/search?word=%D0%BF%D0%BE%D0%B3%D0%BE%D0%B4%D0%B0

**Comment by dolbilov** [comment]
We will use icons from our designer.
